use std::fs::{self, OpenOptions};
use std::io::ErrorKind;
use std::path::PathBuf;
use xxhash_rust::xxh64::xxh64;

fn applications_dir() -> Result<PathBuf, String> {
    let data_home = std::env::var("XDG_DATA_HOME")
        .ok()
        .map(PathBuf::from)
        .or_else(|| {
            std::env::var("HOME")
                .ok()
                .map(|home| PathBuf::from(home).join(".local/share"))
        })
        .ok_or("Failed to resolve applications dir: HOME/XDG_DATA_HOME not set")?;

    let dir = data_home.join("applications");
    fs::create_dir_all(&dir)
        .map_err(|e| format!("Failed to create applications dir {}: {}", dir.display(), e))?;
    Ok(dir)
}

fn sanitize_app_name_for_filename(name: &str) -> String {
    let mut safe_name = String::new();
    let mut last_was_dash = false;

    for ch in name.trim().chars() {
        let normalized = if ch.is_alphanumeric() || matches!(ch, '-' | '_' | '.') {
            let mut lower = ch.to_lowercase().collect::<String>();
            if lower.is_empty() {
                None
            } else {
                if lower.chars().count() > 1 {
                    lower = lower
                        .chars()
                        .filter(|c| c.is_alphanumeric() || matches!(c, '-' | '_' | '.'))
                        .collect();
                }
                if lower.is_empty() {
                    None
                } else {
                    Some(lower)
                }
            }
        } else if ch.is_whitespace() || matches!(ch, '/' | '\\') {
            Some("-".to_string())
        } else {
            Some("-".to_string())
        };

        if let Some(part) = normalized {
            if part == "-" {
                if !safe_name.is_empty() && !last_was_dash {
                    safe_name.push('-');
                }
                last_was_dash = true;
            } else {
                safe_name.push_str(&part);
                last_was_dash = false;
            }
        }
    }

    let safe_name = safe_name.trim_matches('-');
    if safe_name.is_empty() {
        "app".to_string()
    } else {
        safe_name.to_string()
    }
}

fn stable_name_suffix(name: &str) -> String {
    format!("{:08x}", xxh64(name.as_bytes(), 0))
}

fn desktop_file_path(name: &str) -> Result<PathBuf, String> {
    let safe_name = sanitize_app_name_for_filename(name);
    let suffix = stable_name_suffix(name);
    Ok(applications_dir()?.join(format!("{}-{}.desktop", safe_name, suffix)))
}

fn validate_desktop_field(label: &str, value: &str) -> Result<(), String> {
    if value.contains(['\n', '\r', '\0']) {
        return Err(format!(
            "Invalid {}: embedded newline or NUL is not allowed",
            label
        ));
    }
    Ok(())
}

fn is_valid_desktop_entry_file(path: &PathBuf) -> Result<bool, String> {
    let metadata = fs::metadata(path)
        .map_err(|e| format!("Failed to stat desktop entry {}: {}", path.display(), e))?;
    if !metadata.is_file() {
        return Ok(false);
    }

    let content = fs::read_to_string(path)
        .map_err(|e| format!("Failed to read desktop entry {}: {}", path.display(), e))?;
    Ok(content.contains("[Desktop Entry]"))
}

pub fn ensure_desktop_entry(name: &str, exec_command: &str) -> Result<PathBuf, String> {
    validate_desktop_field("Name", name)?;
    validate_desktop_field("Exec", exec_command)?;

    let path = desktop_file_path(name)?;
    if path.exists() {
        if is_valid_desktop_entry_file(&path)? {
            log::info!("Reusing existing desktop entry: {}", path.display());
            return Ok(path);
        }
        return Err(format!(
            "Desktop entry path exists but is not a valid desktop file: {}",
            path.display()
        ));
    }

    let content = format!(
        "# Generated by iVnc\n[Desktop Entry]\nVersion=1.0\nType=Application\nName={}\nExec={}\nTerminal=false\nCategories=Utility;\n",
        name,
        exec_command,
    );
    let tmp_path = path.with_extension(format!("desktop.tmp-{}", std::process::id()));

    match OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&tmp_path)
    {
        Ok(mut file) => {
            use std::io::Write;
            if let Err(e) = file.write_all(content.as_bytes()) {
                let _ = fs::remove_file(&tmp_path);
                return Err(format!(
                    "Failed to write desktop entry {}: {}",
                    path.display(),
                    e
                ));
            }
        }
        Err(e) if e.kind() == ErrorKind::AlreadyExists => {
            let _ = fs::remove_file(&tmp_path);
            return Err(format!(
                "Temporary desktop entry path already exists: {}",
                tmp_path.display()
            ));
        }
        Err(e) => {
            return Err(format!(
                "Failed to create desktop entry {}: {}",
                tmp_path.display(),
                e
            ));
        }
    }

    if let Err(e) = fs::hard_link(&tmp_path, &path) {
        let _ = fs::remove_file(&tmp_path);
        if e.kind() == ErrorKind::AlreadyExists && is_valid_desktop_entry_file(&path)? {
            log::info!("Reusing existing desktop entry: {}", path.display());
            return Ok(path);
        }
        return Err(format!(
            "Failed to move desktop entry into place {}: {}",
            path.display(),
            e
        ));
    }
    let _ = fs::remove_file(&tmp_path);

    log::info!("Created desktop entry: {}", path.display());
    Ok(path)
}
